### ISSUE TITLE
Error on replicache when installing

### ISSUE THREAD

**Issue by asitemade4u** [xvvvyz/lliist#1]
Hi,
I am trying to install llist on Node as per your instructions and I get this error:
```log
error - ./src/components/ReplicacheProvider/index.tsx:2:0
Module not found: Can't resolve 'replicache-nextjs/lib/frontend'
  1 | import { ReactNode } from 'react';
> 2 | import { useReplicache } from 'replicache-nextjs/lib/frontend';
  3 | import ReplicacheContext from '../../context/replicache';
  4 | import { IdSize, LocalstorageKey } from '../../enums';
  5 | import mutations from '../../mutations';
```
Please help.
Thanks,
S.

**Comment by xvvvyz** [comment]
Hi @asitemade4u, did you run `npm install`?

Edit: Nevermind. I was able to reproduce it. Looking into it now.

Edit 2: This should be fixed in the latest commit. Closing, but let me know if you still have issues.

**Comment by asitemade4u** [comment]
Confirmed: it worked and your app is outstanding!
